services:
  dynamic-agent:
    image: hero0ncloud/dynamic-agent:latest
    container_name: dynamic-agent
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      VECTOR_SKIP_VERSION_CHECK: "true" 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped