version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  dynamic-agent:
    image: hero0ncloud/dynamic-agent:latest
    container_name: dynamic-agent
    depends_on:
      - qdrant
    ports:
      - "4000:4000"

    # load environment variables from .env-agent
    env_file:
      - .env-agent

    # overrides or additional vars
    environment:
      SERVER_ADDR: "0.0.0.0:4000"
      VECTOR_TYPE: "qdrant"
      VECTOR_HOST: "http://qdrant:6333"
      VECTOR_INDEX_NAME: "my_documents"
      VECTOR_DIMENSION: "768"
      CHAT_LLM_TYPE: "ollama"
      EMBEDDING_LLM_TYPE: "ollama"

    restart: unless-stopped

volumes:
  qdrant_data: